apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
__RESOURCES__
namespace: sonataflow-infra

configurations:
- config/image-configuration.yaml

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
  - envs:
      - secret.properties
    name: F05EB00E.D9D7.46B1.BC27.136EB02E22E1-secret
configMapGenerator:
  - envs:
      - config.properties
    name: F05EB00E.D9D7.46B1.BC27.136EB02E22E1-gitops

# Replace dev profile in SonataFlow instance(s), add image and envFrom
patches:
- path: sonataflow-patch.yaml
  target:
    kind: SonataFlow
    name: F05EB00E.D9D7.46B1.BC27.136EB02E22E1
images:
- name: serverless-workflow-F05EB00E.D9D7.46B1.BC27.136EB02E22E1
  newName: quay.io/jkilzi/my-workflow
  newTag: __IMAGE_TAG__
