apiVersion: sonataflow.org/v1alpha08
kind: SonataFlow
metadata:
  name: F05EB00E.D9D7.46B1.BC27.136EB02E22E1
  annotations:
    sonataflow.org/profile: prod
  labels:
    backstage.io/kubernetes-id: F05EB00E.D9D7.46B1.BC27.136EB02E22E1
spec:
  persistence:
    postgresql:
      secretRef:
        name: sonataflow-psql-postgresql
        userKey: postgres-username
        passwordKey: postgres-password
      serviceRef:
        name: sonataflow-psql-postgresql
        namespace: sonataflow-infra
        port: 5432
        databaseName: sonataflow
        databaseSchema: F05EB00E.D9D7.46B1.BC27.136EB02E22E1
  podTemplate:
    container:
      image: serverless-workflow-F05EB00E.D9D7.46B1.BC27.136EB02E22E1
      envFrom:
        - configMapRef:
            name: F05EB00E.D9D7.46B1.BC27.136EB02E22E1-gitops
        - secretRef:
            name: F05EB00E.D9D7.46B1.BC27.136EB02E22E1-secret
      resources: {}
